version: '3'

services:

  mysql_db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - /var/lib/docker/volumes/devops-project-volume/_data:/var/lib/mysql

  backend-app:
    image: sofienechihi/my-repo:spring-app-1.0
    restart: on-failure
    depends_on:
      - mysql_db
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    environment:
      - DATABASE_HOST=mysql_db
      - DATABASE_USER=${MYSQLDB_USER}
      - DATABASE_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - DATABASE_NAME=${MYSQLDB_DATABASE}
      - DATABASE_PORT=${MYSQLDB_DOCKER_PORT}
